inherit_from: .rubocop_todo.yml
require: rubocop-performance
inherit_mode:
  merge:
    - Exclude
    - Include

AllCops:
  NewCops: enable
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - config/**/*
    - scratch*.rb
    - Gemfile
    - lib/versionista_service/scraper.rb # This is likely going away anyhow
    # Don't attempt to lint third-party code
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/data/*'
    - 'test/system/**/*'

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - 'lib/versionista_service/*'

Metrics/CyclomaticComplexity:
  Max: 12
  Exclude:
    - 'app/controllers/api/v0/pages_controller.rb'
    - 'app/lib/surt/canonicalize.rb'
    - 'app/jobs/import_versions_job.rb'

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - 'app/jobs/import_versions_job.rb'

Naming/MemoizedInstanceVariableName:
  Exclude:
    # There are some good reasons not to apply this in Rails controllers
    - 'app/controllers/**/*'

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Style/AccessorGrouping:
  Enabled: false

# There are major cases where this cop is just completely wrong. E.g:
#   Array(a_hash)
# Is very much not the same as:
#   [a_hash] unless a_hash.is_a?(Array)
# And will cause you to have a very bad day.
Style/ArrayCoercion:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

# This was mostly all false positives.
Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SafeNavigation:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
