inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/**/*
    - db/schema.rb
    - config/**/*
    - scratch*.rb
    - Gemfile
    - lib/versionista_service/scraper.rb # This is likely going away anyhow
    # Don't attempt to lint third-party code
    - vendor/**/*

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - 'lib/versionista_service/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentHash:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SafeNavigation:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
