inherit_from: .rubocop_todo.yml
require: rubocop-performance
inherit_mode:
  merge:
    - Exclude
    - Include

AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - bin/**/*
    - db/schema.rb
    - config/**/*
    - scratch*.rb
    - Gemfile
    - lib/versionista_service/scraper.rb # This is likely going away anyhow
    # Don't attempt to lint third-party code
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/data/*'

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - 'lib/versionista_service/*'

Metrics/CyclomaticComplexity:
  Max: 12
  Exclude:
    - 'app/controllers/api/v0/pages_controller.rb'
    - 'app/lib/surt/canonicalize.rb'
    - 'app/jobs/import_versions_job.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/jobs/import_versions_job.rb'

Naming/MemoizedInstanceVariableName:
  Exclude:
    # There are some good reasons not to apply this in Rails controllers
    - 'app/controllers/**/*'

Naming/UncommunicativeMethodParamName:
  # TODO: remove this; `to` is going to be added to the default list soon (?)
  # https://github.com/bbatsov/rubocop/pull/5626
  AllowedNames:
    - id
    - io
    - to

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# This was mostly all false positives.
Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SafeNavigation:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
